### PR TITLE
fix(git-action): update config obj

### PR DESCRIPTION
**Pull request by BioPhoton**
Why is the last commit fixing the tests? :D

### CODE REVIEW

**Comment by timdeschryver** [comment]
```
Error: error: Your local changes to the following files would be overwritten by checkout:
    	packages/deprecation-crawler/sandbox/deprecation-crawler.config.json
    Please commit your changes or stash them before you switch branches
```

Should we prevent something by adding a check if we're in CI mode? 🤔

**Comment by BioPhoton** [comment]
I did not really get the problem last time 😅

So I would say yes? :)

**Comment by BioPhoton** [comment]
Is there something left to do here?

**Review by timdeschryver — APPROVED** [review]

**Comment by timdeschryver** [comment]
The only thing left to do is to merge is, and that's now completed ✔

**Pull request merged**
