### PR TITLE
refactor: remove tsconfig

### PR DESCRIPTION
**Pull request by timdeschryver**
To sum it up: 

- removes the need to have a tsconfig
- adds an `include` and `exclude` option to the crawler options
- while crawling, we create a temporary tsconfig file (to find the files to crawl) based on the `include` and `exclude` option. When we have the files, this temporary tsconfig file is removed.

I think with this it will be easier to crawl in a history, and it would also make it easier to implement #97 ? (the passed filter via the cli could just be appended to the config for a single run).

If I remember correctly, we tried a similar approach before but it caused issues because we didn't thought of making this config temporary.

### CODE REVIEW

**Comment by BioPhoton** [comment]
I like the idea because of 2 reasons:
- it makes all the pathFilter, git diffing easier
- we have a deprecation to add! 🤯🤓🤠

Downside:
- it makes it hard to get the right package.json or other things related to multipackage setups
- we loose the ability to have a crawlers root

**Comment by BioPhoton** [comment]
Update:
We could use the config Path

**Comment by timdeschryver** [comment]
Which configPath do you mean? (sorry 😅)
I'm thinking that every package in a repo should have a deprecation config, because the deprecations need to be managed separately from each other. 
How do you expect a mono repo to behave?

**Comment by BioPhoton** [comment]
Exactly like that. I assume everything packed (even in the same version tag) maintains its own deprecations.

The confusing this topic is, the more I see we think the same.

Just agreed!

**Comment by timdeschryver** [comment]
So this PR is OK for you?

**Pull request merged**
